import {
  ShoppingCart,
  Utensils,
  Car,
  Home,
  Plug,
  HeartPulse,
  Clapperboard,
  ShoppingBag,
  Briefcase,
  Laptop,
  Gift,
  CircleDashed,
  Wallet,
  CreditCard,
  Banknote,
  Coins,
  PiggyBank,
  Landmark,
  Plane,
  Bus,
  Train,
  Fuel,
  Coffee,
  Pizza,
  Wine,
  Shirt,
  Dumbbell,
  GraduationCap,
  BookOpen,
  Gamepad2,
  Music,
  Film,
  Phone,
  Wifi,
  Zap,
  Droplet,
  Flame,
  Stethoscope,
  Pill,
  Baby,
  Dog,
  Scissors,
  Hammer,
  Sparkles,
  Tag,
  TrendingUp,
  type LucideProps,
  type LucideIcon,
} from "lucide-react"

// Curated, tree-shaken icon set for categories. Keeps bundle + SW precache
// small (vs. importing the entire lucide set). Unknown names fall back.
const ICONS: Record<string, LucideIcon> = {
  "shopping-cart": ShoppingCart,
  utensils: Utensils,
  car: Car,
  home: Home,
  plug: Plug,
  "heart-pulse": HeartPulse,
  clapperboard: Clapperboard,
  "shopping-bag": ShoppingBag,
  briefcase: Briefcase,
  laptop: Laptop,
  gift: Gift,
  "circle-dashed": CircleDashed,
  wallet: Wallet,
  "credit-card": CreditCard,
  banknote: Banknote,
  coins: Coins,
  "piggy-bank": PiggyBank,
  landmark: Landmark,
  plane: Plane,
  bus: Bus,
  train: Train,
  fuel: Fuel,
  coffee: Coffee,
  pizza: Pizza,
  wine: Wine,
  shirt: Shirt,
  dumbbell: Dumbbell,
  "graduation-cap": GraduationCap,
  "book-open": BookOpen,
  gamepad2: Gamepad2,
  music: Music,
  film: Film,
  phone: Phone,
  wifi: Wifi,
  zap: Zap,
  droplet: Droplet,
  flame: Flame,
  stethoscope: Stethoscope,
  pill: Pill,
  baby: Baby,
  dog: Dog,
  scissors: Scissors,
  hammer: Hammer,
  sparkles: Sparkles,
  tag: Tag,
  "trending-up": TrendingUp,
}

// Names available for the category picker.
export const ICON_NAMES = Object.keys(ICONS)

export function CategoryIcon({ name, ...props }: { name?: string } & LucideProps) {
  const Cmp = (name && ICONS[name]) || CircleDashed
  return <Cmp {...props} />
}
